spring:
  application:
    name: basic-fin-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/basic-fin-tracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
admin:
  super-password: super
